### ISSUE TITLE
Generiek maken van Context zodat deze ook gebruikt kan worden voor Mobile

### ISSUE THREAD

**Issue by KevinvdBurg** [freshheads/analytics-essentials#34]
Op dit moment maken we gebruik van specifieke webcomponenten om events te tracken. Door deze componenten generiek te maken, kunnen we de bibliotheek direct in mobiele projecten inzetten. Dit kan gerealiseerd worden door het introduceren van een interface, waarin we trackEvent en trackPageView definiëren waarin de input en de output staan vermeld. Daarna implementeren we een WebContext en een MobileContext, die elk de specifieke implementaties integreren.

Voorbeelden van componenten die niet werken op mobiele:

- typeof window
- window.location.search
- document.title
- window.location.pathname
- pwa
- searchParams
- sessionStorage

**Comment by martinbroos** [comment]
Als ik er nu naar kijk dan blijft er wel vrij weinig over van die context.tsx op het moment dat je de bovenstaande punten eruit gaat halen. Zouden ook een aparte context provider kunnen maken voor mobile maar wel met dezelfde Event types. En daarbij wel proberen de opzet zoveel mogelijk gelijk te houden. 

Er zal voor de UTM tags dan ook naar een andere manier gekeken moeten worden om die op te slaan. In een cookie met een timeout ? 

Ook die window typeof checks zorgen nu dat het niet in de next server gebruikt kan worden. Maar dat sluit dan ook de mobile implementatie af. Vandaar dat een heel andere provider denk ik duidelijker laat zien wat we willen. 

Is het mogelijk dat jij hier een voorzet voor maakt, je kan het namelijk ook beter testen met react native.

**Comment by KevinvdBurg** [comment]
#35
